apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cd-pipeline-run
spec:
  pipelineRef:
    name: cd-pipeline
  params:
    - name: repo-url
      value: https://github.com/faysal-MMII/devops-capstone-project.git
    - name: branch
      value: main
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
